version: '3.8'

services:
  web:
    build: .
    container_name: reabitech_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3   # Mantém o banco de dados salvo
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-dev
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1