[pytest]
DJANGO_SETTINGS_MODULE = backend.settings
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Testes rápidos e isolados
addopts =
    -v
    --tb=short
    --strict-markers
    --disable-warnings

# Diretório de testes
testpaths = tests

# Marcadores customizados
markers =
    slow: testes que demoram mais
    integration: testes de integração entre apps
