# Generated by Django 6.0.6 on 2026-06-23 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('gratuito', 'Gratuito'), ('profissional', 'Profissional'), ('premium', 'Premium')], max_length=50, unique=True)),
                ('descricao', models.TextField()),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_projetos', models.IntegerField(default=1)),
                ('max_atletas', models.IntegerField(default=10)),
                ('max_profissionais', models.IntegerField(default=2)),
                ('tem_fisioterapia', models.BooleanField(default=True)),
                ('tem_psicologia', models.BooleanField(default=True)),
                ('tem_relatorios', models.BooleanField(default=True)),
                ('tem_graficos', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Parceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=100)),
                ('nome_parceiro', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('mensagem', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('em_analise', 'Em Análise')], default='pendente', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('plano_interesse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos.plano')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='projetos/logos/')),
                ('data_assinatura', models.DateField(auto_now_add=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('pendente', 'Pendente'), ('expirado', 'Expirado')], default='pendente', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('email_contato', models.EmailField(blank=True, max_length=254)),
                ('telefone_contato', models.CharField(blank=True, max_length=20)),
                ('endereco', models.TextField(blank=True)),
                ('coordenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_coordenados', to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos.plano')),
            ],
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='ativa', max_length=20)),
                ('plano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos.plano')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='projetos.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='ProfissionalProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tecnico', 'Técnico'), ('fisioterapeuta', 'Fisioterapeuta'), ('psicologo', 'Psicólogo'), ('nutricionista', 'Nutricionista'), ('preparador', 'Preparador Físico'), ('outro', 'Outro')], max_length=20)),
                ('especialidade', models.CharField(blank=True, max_length=100)),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_profissionais', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='projetos.projeto')),
            ],
            options={
                'unique_together': {('projeto', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='AtletaProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_atleta', to='usuarios.atleta')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atletas', to='projetos.projeto')),
            ],
            options={
                'unique_together': {('projeto', 'atleta')},
            },
        ),
    ]
