# Generated by Django 4.2.30 on 2026-08-11 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_usuarios', models.IntegerField(default=10)),
                ('inclui_fisioterapia', models.BooleanField(default=True)),
                ('inclui_psicologia', models.BooleanField(default=True)),
                ('inclui_relatorios', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('time', 'Time Esportivo'), ('escola', 'Projeto Escolar'), ('clinica', 'Consultório/Clínica'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='projetos/logos/')),
                ('publico', models.BooleanField(default=False)),
                ('site_oficial', models.URLField(blank=True)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos_coordenados', to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projetos.plano')),
            ],
        ),
        migrations.CreateModel(
            name='ConviteProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('tipo_membro', models.CharField(choices=[('coordenador', 'Coordenador'), ('tecnico', 'Técnico'), ('fisioterapeuta', 'Fisioterapeuta'), ('psicologo', 'Psicólogo'), ('atleta', 'Atleta')], max_length=20)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expiracao', models.DateTimeField()),
                ('aceito', models.BooleanField(default=False)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='projetos.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='MembroProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('coordenador', 'Coordenador'), ('tecnico', 'Técnico'), ('fisioterapeuta', 'Fisioterapeuta'), ('psicologo', 'Psicólogo'), ('atleta', 'Atleta')], max_length=20)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='projetos.projeto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_projeto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('projeto', 'usuario')},
            },
        ),
    ]
