# Generated by Django 4.2.30 on 2026-08-25 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_senha_temporaria_alter_atleta_modalidade_and_more'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membroprojeto',
            name='modalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.modalidadeesportiva'),
        ),
        migrations.AddField(
            model_name='membroprojeto',
            name='sexo',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], max_length=20, null=True),
        ),
    ]
