# Generated by Django 4.2.30 on 2026-09-18 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_membroprojeto_modalidade_membroprojeto_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conviteprojeto',
            name='token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='plano',
            name='max_usuarios',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='plano',
            name='preco_mensal',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
