# Generated by Django 4.2.30 on 2026-09-22 13:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_alter_conviteprojeto_token_alter_plano_max_usuarios_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conviteprojeto',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Convite de Projeto', 'verbose_name_plural': 'Convites de Projeto'},
        ),
        migrations.AlterModelOptions(
            name='membroprojeto',
            options={'ordering': ['-entrou_em'], 'verbose_name': 'Membro do Projeto', 'verbose_name_plural': 'Membros do Projeto'},
        ),
        migrations.AlterModelOptions(
            name='plano',
            options={'ordering': ['ordem', 'preco_mensal'], 'verbose_name': 'Plano', 'verbose_name_plural': 'Planos'},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.RemoveField(
            model_name='membroprojeto',
            name='data_entrada',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='inclui_fisioterapia',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='inclui_psicologia',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='inclui_relatorios',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='site_oficial',
        ),
        migrations.AddField(
            model_name='membroprojeto',
            name='entrou_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Destacar na landing page'),
        ),
        migrations.AddField(
            model_name='plano',
            name='max_projetos',
            field=models.IntegerField(default=1, help_text='Quantos projetos o coordenador pode ter', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='plano',
            name='modulos_inclusos',
            field=models.JSONField(default=list, help_text="Lista de módulos: ['fisioterapia', 'psicologia', 'tecnico', 'nutricao']"),
        ),
        migrations.AddField(
            model_name='plano',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Ordem de exibição (menor número primeiro)'),
        ),
        migrations.AddField(
            model_name='plano',
            name='tipo',
            field=models.CharField(choices=[('free', 'Gratuito'), ('pro', 'Profissional'), ('enterprise', 'Empresarial')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='projeto',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='modulos_ativos',
            field=models.JSONField(default=list, help_text='Módulos ativos neste projeto'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='conviteprojeto',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='conviteprojeto',
            name='expiracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conviteprojeto',
            name='tipo_membro',
            field=models.CharField(choices=[('coordenador', 'Coordenador'), ('fisioterapeuta', 'Fisioterapeuta'), ('psicologo', 'Psicólogo'), ('tecnico', 'Técnico'), ('nutricionista', 'Nutricionista'), ('atleta', 'Atleta')], default='atleta', max_length=20),
        ),
        migrations.AlterField(
            model_name='conviteprojeto',
            name='token',
            field=models.CharField(blank=True, default='', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='membroprojeto',
            name='modalidade',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='membroprojeto',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='membroprojeto',
            name='tipo',
            field=models.CharField(choices=[('coordenador', 'Coordenador'), ('fisioterapeuta', 'Fisioterapeuta'), ('psicologo', 'Psicólogo'), ('tecnico', 'Técnico'), ('nutricionista', 'Nutricionista'), ('atleta', 'Atleta')], default='atleta', max_length=20),
        ),
        migrations.AlterField(
            model_name='plano',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='plano',
            name='max_usuarios',
            field=models.IntegerField(default=10, help_text='Número máximo de membros no projeto', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='plano',
            name='preco_mensal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projetos', to='projetos.plano'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='publico',
            field=models.BooleanField(default=False, help_text='Aparecer na landing pública'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tipo',
            field=models.CharField(choices=[('escola', 'Escola / Instituição de Ensino'), ('clinica', 'Clínica de Reabilitação'), ('time', 'Time / Clube Esportivo'), ('academia', 'Academia'), ('projeto_social', 'Projeto Social'), ('outro', 'Outro')], default='outro', max_length=20),
        ),
    ]
