# Generated by Django 4.2.30 on 2026-09-25 11:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projetos', '0004_alter_conviteprojeto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='data_expiracao_trial',
            field=models.DateTimeField(blank=True, help_text='Data em que o trial expira (null = sem expiração)', null=True, verbose_name='Expiração do Trial'),
        ),
        migrations.AlterField(
            model_name='conviteprojeto',
            name='aceito',
            field=models.BooleanField(default=False, verbose_name='Aceito'),
        ),
        migrations.AlterField(
            model_name='conviteprojeto',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='conviteprojeto',
            name='expiracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expira em'),
        ),
        migrations.AlterField(
            model_name='conviteprojeto',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='projetos.projeto', verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='conviteprojeto',
            name='tipo_membro',
            field=models.CharField(choices=[('coordenador', 'Coordenador / Admin'), ('fisioterapeuta', 'Fisioterapeuta'), ('psicologo', 'Psicólogo'), ('tecnico', 'Técnico / Professor'), ('atleta', 'Paciente / Aluno / Atleta')], default='atleta', max_length=20, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='conviteprojeto',
            name='token',
            field=models.CharField(blank=True, default='', max_length=64, unique=True, verbose_name='Token do Convite'),
        ),
        migrations.AlterField(
            model_name='membroprojeto',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='membroprojeto',
            name='entrou_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Entrou em'),
        ),
        migrations.AlterField(
            model_name='membroprojeto',
            name='modalidade',
            field=models.CharField(blank=True, default='', help_text='Ex: Futebol, Reabilitação, Pós-operatório, etc.', max_length=100, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='membroprojeto',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='projetos.projeto', verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='membroprojeto',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='membroprojeto',
            name='tipo',
            field=models.CharField(choices=[('coordenador', 'Coordenador / Admin'), ('fisioterapeuta', 'Fisioterapeuta'), ('psicologo', 'Psicólogo'), ('tecnico', 'Técnico / Professor'), ('atleta', 'Paciente / Aluno / Atleta')], default='atleta', max_length=20, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='membroprojeto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_projeto', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Destacar na landing page (recomendado)', verbose_name='Destacado'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='max_projetos',
            field=models.IntegerField(default=1, help_text='Quantos projetos o coordenador pode ter (0 = ilimitado)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máximo de Projetos'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='max_usuarios',
            field=models.IntegerField(default=10, help_text='Número máximo de membros (0 = ilimitado)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máximo de Usuários'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='modulos_inclusos',
            field=models.JSONField(default=list, help_text="Lista de módulos: ['fisioterapia', 'psicologia', 'tecnico']", verbose_name='Módulos Inclusos'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Plano'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Ordem de exibição (menor primeiro)', verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='preco_mensal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Mensal (R$)'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='tipo',
            field=models.CharField(choices=[('trial', 'Trial Grátis (30 dias)'), ('profissional', 'Profissional'), ('empresarial', 'Empresarial')], default='trial', max_length=20, verbose_name='Tipo do Plano'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='coordenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos_coordenados', to=settings.AUTH_USER_MODEL, verbose_name='Coordenador Responsável'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='projetos/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='modulos_ativos',
            field=models.JSONField(default=list, help_text="Módulos ativos: ['fisioterapia', 'psicologia', 'tecnico']", verbose_name='Módulos Ativos'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome do Projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projetos', to='projetos.plano', verbose_name='Plano Contratado'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='publico',
            field=models.BooleanField(default=False, help_text='Aparecer na landing page pública', verbose_name='Público'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=160, unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tipo',
            field=models.CharField(choices=[('clinica', 'Clínica de Fisioterapia / Reabilitação'), ('escola', 'Escola / Instituição de Ensino'), ('time', 'Time / Clube Esportivo'), ('academia', 'Academia'), ('projeto_social', 'Projeto Social'), ('consultorio', 'Consultório Individual'), ('outro', 'Outro')], default='clinica', max_length=20, verbose_name='Tipo'),
        ),
    ]
