# Generated by Django 6.0.6 on 2026-10-03 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompartilhamentoProntuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liberado_em', models.DateTimeField(auto_now_add=True, verbose_name='Liberado em')),
                ('pode_comentar', models.BooleanField(default=True, help_text='Se marcado, o técnico pode adicionar observações de treino', verbose_name='Pode comentar')),
                ('observacao_liberacao', models.TextField(blank=True, help_text='Mensagem opcional do fisio para o técnico (ex: foco em fortalecer quadríceps)', verbose_name='Observação da Liberação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('liberado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prontuarios_liberados', to=settings.AUTH_USER_MODEL, verbose_name='Liberado por')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentos', to='prontuario.prontuario', verbose_name='Prontuário')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prontuarios_compartilhados', to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Compartilhamento de Prontuário',
                'verbose_name_plural': 'Compartilhamentos de Prontuário',
                'ordering': ['-liberado_em'],
                'unique_together': {('prontuario', 'tecnico')},
            },
        ),
        migrations.CreateModel(
            name='ObservacaoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('treino', 'Treino Regular'), ('recuperacao', 'Sessão de Recuperação'), ('ocorrencia', 'Ocorrência / Incidente'), ('desempenho', 'Avaliação de Desempenho'), ('comportamento', 'Comportamento / Atitude'), ('outro', 'Outro')], default='treino', max_length=20, verbose_name='Tipo de Observação')),
                ('nivel_impacto', models.CharField(choices=[('positivo', 'Impacto Positivo'), ('neutro', 'Neutro'), ('atencao', 'Requer Atenção'), ('critico', 'Crítico')], default='neutro', max_length=20, verbose_name='Nível de Impacto')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('desempenho_treino', models.IntegerField(blank=True, help_text='Como o atleta se saiu no treino (0-10)', null=True, verbose_name='Desempenho no Treino')),
                ('dor_relatada', models.IntegerField(blank=True, help_text='Dor relatada pelo atleta durante o treino (0-10)', null=True, verbose_name='Dor Relatada')),
                ('aderencia', models.IntegerField(blank=True, help_text='Adesão ao programa proposto (0-10)', null=True, verbose_name='Adesão ao Programa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('compartilhamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacoes', to='prontuario.compartilhamentoprontuario', verbose_name='Compartilhamento')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacoes_tecnico', to='prontuario.prontuario', verbose_name='Prontuário')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacoes_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Observação do Técnico',
                'verbose_name_plural': 'Observações dos Técnicos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
