# Generated by Django 4.2.30 on 2026-08-14 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
        ('psicologia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaopsicologica',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_psico', to='projetos.projeto'),
        ),
        migrations.AddField(
            model_name='questionarioperiodico',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionarios', to='projetos.projeto'),
        ),
    ]
