# Generated by Django 6.0.3 on 2026-06-11 14:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolucaoFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('dor', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('fadiga', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('desempenho', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('observacoes', models.TextField(blank=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes', to='usuarios.atleta')),
                ('estagiario_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='Lesao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('muscular', 'Muscular'), ('ligamentar', 'Ligamentar'), ('osseo', 'Ósseo'), ('tendinite', 'Tendinite'), ('fratura', 'Fratura'), ('outro', 'Outro')], max_length=20)),
                ('gravidade', models.CharField(choices=[('leve', 'Leve - 1 a 2 semanas'), ('moderada', 'Moderada - 3 a 6 semanas'), ('grave', 'Grave - Mais de 6 semanas')], max_length=10)),
                ('local', models.CharField(max_length=100)),
                ('data_ocorrencia', models.DateField()),
                ('descricao', models.TextField()),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesoes', to='usuarios.atleta')),
                ('fisioterapeuta_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesoes_atendidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TratamentoFisioterapico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_previsao_termino', models.DateField(blank=True, null=True)),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('lesao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamentos', to='fisioterapia.lesao')),
            ],
        ),
        migrations.CreateModel(
            name='ExercicioRecuperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('series', models.IntegerField()),
                ('repeticoes', models.IntegerField()),
                ('frequencia', models.CharField(max_length=100)),
                ('video_url', models.URLField(blank=True)),
                ('tratamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='fisioterapia.tratamentofisioterapico')),
            ],
        ),
    ]
