# Generated by Django 4.2.30 on 2026-08-14 14:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
        ('fisioterapia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucaofisica',
            name='mobilidade',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='evolucaofisica',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes', to='projetos.projeto'),
        ),
        migrations.AddField(
            model_name='exerciciorecuperacao',
            name='check_realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exerciciorecuperacao',
            name='data_realizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='lesoes/'),
        ),
        migrations.AddField(
            model_name='lesao',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesoes', to='projetos.projeto'),
        ),
        migrations.AlterField(
            model_name='exerciciorecuperacao',
            name='frequencia',
            field=models.CharField(default='3x por semana', max_length=100),
        ),
        migrations.AlterField(
            model_name='exerciciorecuperacao',
            name='repeticoes',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='exerciciorecuperacao',
            name='series',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='tratamentofisioterapico',
            name='data_inicio',
            field=models.DateField(auto_now_add=True),
        ),
    ]
