# Generated by Django 4.2.30 on 2026-09-08 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisioterapia', '0002_evolucaofisica_mobilidade_evolucaofisica_projeto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evolucaofisica',
            name='fadiga',
        ),
        migrations.AddField(
            model_name='evolucaofisica',
            name='flexibilidade',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='evolucaofisica',
            name='forca',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='evolucaofisica',
            name='resistencia',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='exerciciorecuperacao',
            name='dificuldade',
            field=models.IntegerField(choices=[(1, 'Fácil'), (2, 'Médio'), (3, 'Difícil')], default=1),
        ),
        migrations.AddField(
            model_name='exerciciorecuperacao',
            name='dificuldade_percebida',
            field=models.IntegerField(blank=True, choices=[(1, 'Muito fácil'), (2, 'Fácil'), (3, 'Médio'), (4, 'Difícil'), (5, 'Muito difícil')], null=True),
        ),
        migrations.AddField(
            model_name='exerciciorecuperacao',
            name='dor_durante_exercicio',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='exerciciorecuperacao',
            name='duracao_minutos',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='exerciciorecuperacao',
            name='grupo_muscular',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='exerciciorecuperacao',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesao',
            name='causa',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lesao',
            name='diagnostico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesao',
            name='lado',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lesao',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesao',
            name='previsao_recuperacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesao',
            name='regiao_corporal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lesao',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('em_tratamento', 'Em Tratamento'), ('recuperada', 'Recuperada'), ('cronica', 'Crônica')], default='ativa', max_length=20),
        ),
    ]
