# Generated by Django 4.2.30 on 2026-08-14 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='senha_temporaria',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='modalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.modalidadeesportiva'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('coordenador', 'Coordenador'), ('tecnico', 'Técnico'), ('fisioterapeuta', 'Fisioterapeuta'), ('psicologo', 'Psicólogo'), ('atleta', 'Atleta')], max_length=20),
        ),
    ]
