# Generated by Django 4.2.30 on 2026-09-08 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0004_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dor_alta', 'Dor Alta'), ('falta_exercicio', 'Falta de Exercício'), ('evolucao_baixa', 'Evolução Baixa'), ('avaliacao_pendente', 'Avaliação Pendente'), ('tratamento_prazo', 'Tratamento no Prazo'), ('recuperacao_estagnada', 'Recuperação Estagnada')], max_length=30)),
                ('mensagem', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='usuarios.atleta')),
            ],
        ),
    ]
