# Generated by Django 4.2.30 on 2026-09-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_notificacao_link_auditoria_alerta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacao',
            options={'ordering': ['-criada_em']},
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['usuario', 'lida'], name='usuarios_no_usuario_bff7d0_idx'),
        ),
    ]
