# Generated by Django 6.0.6 on 2026-10-03 03:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_projeto_data_expiracao_trial_and_more'),
        ('usuarios', '0006_alter_notificacao_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoria',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Auditoria', 'verbose_name_plural': 'Auditorias'},
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='data',
        ),
        migrations.AddField(
            model_name='auditoria',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data/Hora'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditoria',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='modelo',
            field=models.CharField(blank=True, help_text='Ex: Prontuario, Lesao, Atleta', max_length=100, verbose_name='Modelo Afetado'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='objeto_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID do Objeto'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='objeto_repr',
            field=models.CharField(blank=True, help_text='String do objeto no momento da ação', max_length=300, verbose_name='Representação do Objeto'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='projetos.projeto', verbose_name='Projeto'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='user_agent',
            field=models.CharField(blank=True, max_length=300, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='acao',
            field=models.CharField(choices=[('criar', 'Criação'), ('editar', 'Edição'), ('deletar', 'Exclusão'), ('visualizar', 'Visualização'), ('login', 'Login'), ('logout', 'Logout'), ('exportar', 'Exportação'), ('importar', 'Importação')], max_length=20, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição Detalhada'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['usuario', '-criado_em'], name='usuarios_au_usuario_4a6c1e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['modelo', 'objeto_id'], name='usuarios_au_modelo_211e39_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['-criado_em'], name='usuarios_au_criado__c57996_idx'),
        ),
    ]
