# Generated by Django 6.0.6 on 2026-10-04 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0006_alter_membroprojeto_modalidade_and_more'),
        ('usuarios', '0007_alter_auditoria_options_remove_auditoria_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('avaliacao_inicial', 'Avaliação Inicial'), ('fisioterapia', 'Sessão de Fisioterapia'), ('psicologia', 'Sessão de Psicologia'), ('retorno', 'Retorno'), ('reavaliacao', 'Reavaliação'), ('alta', 'Alta'), ('outro', 'Outro')], default='fisioterapia', max_length=25, verbose_name='Tipo de Consulta')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('faltou', 'Faltou'), ('remarcada', 'Remarcada')], default='agendada', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20, verbose_name='Prioridade')),
                ('modalidade', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online'), ('domiciliar', 'Domiciliar')], default='presencial', max_length=20, verbose_name='Modalidade')),
                ('data', models.DateField(help_text='Data da consulta', verbose_name='Data')),
                ('hora_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('hora_fim', models.TimeField(verbose_name='Horário de Término')),
                ('local', models.CharField(blank=True, help_text='Ex: Sala 2, Clínica Central, Link Meet', max_length=200, verbose_name='Local')),
                ('motivo', models.TextField(blank=True, help_text='Motivo da consulta (opcional)', verbose_name='Motivo / Objetivo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='Motivo do Cancelamento')),
                ('lembrete_enviado', models.BooleanField(default=False, verbose_name='Lembrete Enviado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('realizada_em', models.DateTimeField(blank=True, null=True)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='usuarios.atleta', verbose_name='Atleta / Paciente')),
                ('consulta_original', models.ForeignKey(blank=True, help_text='Preenchido quando esta consulta é uma remarcação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remarcacoes', to='consultas.consulta', verbose_name='Consulta Original')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_como_profissional', to=settings.AUTH_USER_MODEL, verbose_name='Profissional Responsável')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='projetos.projeto', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['data', 'hora_inicio'],
                'indexes': [models.Index(fields=['projeto', 'data'], name='consultas_c_projeto_97e912_idx'), models.Index(fields=['atleta', 'data'], name='consultas_c_atleta__482dc9_idx'), models.Index(fields=['profissional', 'data'], name='consultas_c_profiss_8d22c7_idx'), models.Index(fields=['status', 'data'], name='consultas_c_status_56f100_idx')],
            },
        ),
    ]
