# Generated by Django 6.0.6 on 2026-10-04 15:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0006_alter_membroprojeto_modalidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dm', 'Conversa Direta'), ('grupo', 'Grupo')], default='dm', max_length=10, verbose_name='Tipo')),
                ('nome', models.CharField(blank=True, default='', help_text='Obrigatório apenas para grupos', max_length=150, verbose_name='Nome do Grupo')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='Última movimentação')),
                ('criada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='projetos.projeto', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-atualizada_em'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('anexo', models.FileField(blank=True, help_text='Imagem ou PDF (máx 10MB)', null=True, upload_to='mensageria/anexos/%Y/%m/', verbose_name='Anexo')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviada em')),
                ('editada_em', models.DateTimeField(blank=True, null=True, verbose_name='Editada em')),
                ('deletada', models.BooleanField(default=False, verbose_name='Deletada')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='mensageria.conversa', verbose_name='Conversa')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['criada_em'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteConversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrou_em', models.DateTimeField(auto_now_add=True, verbose_name='Entrou em')),
                ('ultima_leitura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última leitura')),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='mensageria.conversa', verbose_name='Conversa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_conversa', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Participante de Conversa',
                'verbose_name_plural': 'Participantes de Conversa',
                'ordering': ['entrou_em'],
            },
        ),
        migrations.AddIndex(
            model_name='conversa',
            index=models.Index(fields=['projeto', '-atualizada_em'], name='mensageria__projeto_9ae7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['conversa', 'criada_em'], name='mensageria__convers_14e1a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participanteconversa',
            unique_together={('conversa', 'usuario')},
        ),
    ]
