# Generated by Django 4.2.30 on 2026-08-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('esporte', models.CharField(max_length=100)),
                ('lesao', models.CharField(max_length=200)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('Recuperando', 'Recuperando'), ('Atenção', 'Atenção'), ('Crítico', 'Crítico'), ('Liberado', 'Liberado')], default='Recuperando', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='atletas/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
