# Generated by Django 6.0.4 on 2026-05-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('esporte', models.CharField(max_length=100)),
                ('lesao', models.CharField(max_length=200)),
            ],
        ),
    ]
