# Generated by Django 6.0.4 on 2026-05-11 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=1.7, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atleta',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atleta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='atletas/'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=70, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atleta',
            name='status',
            field=models.CharField(choices=[('Recuperando', 'Recuperando'), ('Atenção', 'Atenção'), ('Crítico', 'Crítico'), ('Liberado', 'Liberado')], default='Recuperando', max_length=20),
        ),
    ]
